(define (problem Pochi-Campi)
  (:domain CAMPI)
  (:objects traA1 traA2 aratro1 seminatore1 seminatore2
     contadino1 contadino2
     cam1 cam2 cam3 cam4 cam5)
  (:init
   (contadino contadino1)
   (contadino contadino2)
   (CAMPO cam1)
   (CAMPO cam2)
   (CAMPO cam3)
   (CAMPO cam4)
   (CAMPO cam5)
   (TRA traA1)
   (TRA traA2)
   (TRA-ARA traA1)
   (TRA-ARA traA2)
   (TRA-SEMINA traA1)
   (TRA-SEMINA traA2)
   (ARATRO aratro1)
   (SEMINATORE seminatore1)
   (SEMINATORE seminatore2)
   (CONNESSO cam1 cam2)
   (CONNESSO cam2 cam1)
   (CONNESSO cam2 cam3)
   (CONNESSO cam3 cam2)
   (CONNESSO cam3 cam4)
   (CONNESSO cam4 cam3)
   (CONNESSO cam4 cam5)
   (CONNESSO cam5 cam4)
   
   (at traA1 cam1);; dynamic predicates
   (at traA2 cam5)
   (at aratro1 cam1)
   (at seminatore1 cam1)
   (at seminatore2 cam5)
   (at contadino1 cam1)
   (at contadino2 cam5)
;;   (seminato cam1)
;;   (seminato cam2)
   )
   
  (:goal (and
   (innaffiato cam1)
   (innaffiato cam2)))
  )